#!/bin/bash

echo "This will install 7zip and stress-ng. Continue? [Y/n]"
read -r response

if [[ "$response" =~ ^[Nn]$ ]]; then
    echo "Installation aborted."
    exit 0
fi

install_failed() {
    echo "There has been an error. Please manually install 7zip and stress-ng to use threadstepper."
    exit 1
}

if command -v pacman &>/dev/null; then
    sudo pacman -Sy --noconfirm stress-ng || install_failed
    sudo pacman -Sy --noconfirm p7zip || install_failed
elif command -v apt &>/dev/null; then
    sudo apt update && sudo apt install -y p7zip-full stress-ng || install_failed
elif command -v dnf &>/dev/null; then
    sudo dnf install -y p7zip stress-ng || install_failed
elif command -v zypper &>/dev/null; then
    sudo zypper install -y p7zip stress-ng || install_failed
else
    echo "Unsupported package manager"
    install_failed
fi

echo "Dependancies have been installed"

APPIMAGE_URL="https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/releases/download/133.0.6943.126-1/ungoogled-chromium_133.0.6943.126-1.AppImage"
APPIMAGE_PATH="tests/browser/ungoogled-chromium_133.0.6943.126-1.AppImage"

mkdir -p tests/browser
if [ ! -f "$APPIMAGE_PATH" ]; then
    echo "Downloading ungoogled-chromium AppImage..."
    wget -O "$APPIMAGE_PATH" "$APPIMAGE_URL" || { echo "Download failed"; exit 1; }
    chmod +x "$APPIMAGE_PATH"
else
    echo "AppImage already exists at $APPIMAGE_PATH"
fi

chmod +x ./threadstepper

echo "You can now launch ./threadstepper to start testing."
