#!/bin/bash

trap cleanup SIGINT SIGTERM

# ------ Includes
# Settings
source ./config/user.settings
# Operation
source ./functions/topology.sh
source ./functions/testing.sh
source ./functions/general.sh
source ./functions/errors.sh
# Stressors
source ./functions/stressors/all_core.sh
source ./functions/stressors/load_test.sh
# Tests
source ./functions/tests/single/browser.sh
source ./functions/tests/single/cores.sh
source ./functions/tests/low/rapid.sh
source ./functions/tests/low/random.sh
source ./functions/tests/all_core/cumulative.sh
# ------------

# Setup
electon_bin=$(compgen -c | grep '^electron[0-9]' | sort -V | tail -1)
initial_output

# Clear ram cache
echo 3 | sudo tee /proc/sys/vm/drop_caches >/dev/null 2>&1

# Calculate cores
num_cores=$(nproc)
num_cores=${num_cores:-1}
physical_cores=$((num_cores / 2))

# Get run vars
loops=${loops:-1}
rapid_tests=${rapid_tests:-0}
start_core=${start_core:-0}
rest_time=${rest_time:-1}
update_progress "Startup" $loop_counter $loops 

# main loop
start_time=$seconds
for ((loop_counter=1; loop_counter<=loops; loop_counter++)); do
    # Init vars
    elapsed=$((seconds - start_time))
    elapsed_formatted=$(printf "%02d:%02d:%02d" $((elapsed/3600)) $(((elapsed/60)%60)) $((elapsed%60)))
    end_core=$((physical_cores - 2))
    # Startup
    if [[ "$loop_counter" -gt 1 ]]; then
        echo "$(tput setaf 5)Running loop $loop_counter of $loops ($elapsed_formatted)$(tput sgr0)" | tee -a "$output_log_file"
    else
        echo "$(tput setaf 5)Starting loop $loop_counter of $loops $(tput sgr0)" | tee -a "$output_log_file"
    fi
    # All core tests
    if [ "$all_core_time" -eq 0 ] || [ "$all_core_tests" -eq 0 ]; then
        echo "$(tput setaf 4)All Core tests are disabled, skipping! $(tput sgr0)" | tee -a "$output_log_file"
    else
        all_core_runner
    fi
    # Rapid tests
    if [ "$rapid_time" -eq 0 ] || [ "$rapid_tests" -eq 0 ]; then
        echo "$(tput setaf 4)Rapid tests are disabled, skipping! $(tput sgr0)" | tee -a "$output_log_file"
    else
        rapid_runner
    fi
    # Random tests
    if [ "$random_time" -eq 0 ] || [ "$random_tests" -eq 0 ]; then
        echo "$(tput setaf 4)Random tests are disabled, skipping! $(tput sgr0)" | tee -a "$output_log_file"
    else
        rand_runner
    fi
    # Single core tests
    if [ "$light_time" -eq 0 ] && [ "$medium_time" -eq 0 ] && [ "heavy_time" -eq 0 ]; then
        echo "$(tput setaf 4)Single Core tests are disabled, skipping! $(tput sgr0)" | tee -a "$output_log_file"
    else
        single_core_runner "$start_core" "$end_core"
    fi
    # Finish loop
    highest_clock="$(<"$current_dir/logs/clock.log") Ghz"
    higest_temp="$(<"$current_dir/logs/temperature.log") C"
    finished_loops=$loop_counter
    echo "$(tput setaf 8)Highest CPU Clock: $highest_clock" | tee -a "$output_log_file"
    echo "$(tput setaf 8)Highest CPU Temperature: $highest_clock" | tee -a "$output_log_file"
done

# Fin
highest_clock="$(<"$current_dir/logs/clock.log") Ghz"
elapsed=$((seconds - start_time))
elapsed_formatted=$(printf "%02d:%02d:%02d" $((elapsed/3600)) $(((elapsed/60)%60)) $((elapsed%60)))

echo "$(tput setaf 3)Loops $finished_loops/$loops completed! ($elapsed_formatted)$(tput sgr0)" | tee -a "$output_log_file"
echo "$(tput setaf 8)[DEBUG] Highest CPU Clock: $highest_clock" | tee -a "$output_log_file"

cleanup